name: Docker Image CI

on:
  push:
    branches: [ "docker-build" ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tag
      id: image-tag
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG="ghcr.io/${REPO_OWNER}/cosmos-explorer-base:${{ github.sha }}"
        LATEST_TAG="ghcr.io/${REPO_OWNER}/cosmos-explorer-base:latest"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file containers/explorer-base.Dockerfile --tag ${{ steps.image-tag.outputs.IMAGE_TAG }} --tag ${{ steps.image-tag.outputs.LATEST_TAG }}

    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker push ${{ steps.image-tag.outputs.IMAGE_TAG }}
        docker push ${{ steps.image-tag.outputs.LATEST_TAG }}
